- name: Deploy Spring Boot App
  hosts: localhost
  become: yes
  tasks:
    - name: Stop existing container
      shell: docker rm -f student-app || true

    - name: Run Spring Boot container
      shell: docker run -d -p 8081:8081 --name student-app student-tracker-backend
